---

ot_v6_mumbai:
  hosts:
    ot_v6_mumba1_1:
      ansible_host: gate.hidora.com
      ansible_python_interpreter: /usr/bin/python3
#      ansible_user: 109622-2082
      ansible_user: 109929-2082
      ansible_port: 3022