- name: Install nodejs and npm
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "nodejs" }
    - { state: "latest", name: "npm" }

- name: Install "forever" node.js package globally.
  npm:
    name: forever
    global: yes