---
- name: Install general purpose/common packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "latest", name: "aptitude" }
    - { state: "latest", name: "htop" }
    - { state: "latest", name: "git-all" }

- name: Create ansible directory in the home directory
  ansible.builtin.file:
    path: ./ansible
    state: directory